version: '3.7'

services:

  sample:
    container_name: html-web
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8087:80'
    environment:
      - NODE_ENV=development
